name: ${project.artifactId}
version: ${project.version}
description: ${project.description}
author: Jack Henhapl
api-version: 1.13
main: edu.whimc.observations.Observations
load: POSTWORLD
depend: [HolographicDisplays, ProtocolLib]
softdepend: [Multiverse-Core]
loadbefore: [Quests]
commands:
  observe:
    description: Create an observation
    usage: '/observe [text]'
  adminobservations:
    description: Manage observations
    usage: '/adminobservations'
