# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Maven

on: [pull_request, push]

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          fail_on_error: true
          reporter: 'github-pr-check'
          tool_name: 'checkstyle'
          level: error
          filter_mode: nofilter
          checkstyle_config: checkstyle.xml

  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn package
      - name: Test with Maven
        run: mvn test
